package uk.ac.nottingham.cryptography;

/**
 * Helper class that encapsulates two arrays holding key pairs.
 * <br/>
 * Do not edit this file.
 */
public final class CASTKeySet {
    private final int[] m;
    private final int[] r;

    public CASTKeySet(int[] M, int[] R) {
        this.m = M;
        this.r = R;
    }

    public int[] getM() {
        return m;
    }

    public int[] getR() {
        return r;
    }
}
